# Generated by Django 4.2.7 on 2024-02-19 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cwiczenie_budowa_masy_miesniowej',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('ilosc_pow', models.IntegerField()),
                ('partia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cwiczenie_utrata_wagi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('ilosc_pow', models.IntegerField()),
                ('partia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cwiecznie_poprawa_wytrzymalosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('ilosc_pow', models.IntegerField()),
                ('partia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanTreningowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waga', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wzrost', models.IntegerField()),
                ('cel', models.CharField(choices=[('utrata-wagi', 'Utrata Wagi'), ('poprawa-wytrzymalosci', 'Poprawa Wytrzymalosci'), ('budowa-masy-miesniowej', 'Budowa Masy Miesniowej')], max_length=100)),
                ('wiek', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plec', models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta')], max_length=1)),
                ('kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanCwiczen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cwiczenie_id', models.CharField(max_length=100)),
                ('cwiczenie_typ', models.CharField(max_length=100)),
                ('dzien', models.IntegerField()),
                ('plan_treningowy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cwiczenia', to='crosfat.plantreningowy')),
            ],
        ),
    ]
