# Generated by Django 5.0 on 2024-02-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crosfat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cwizcenie',
            new_name='cwiczenie',
        ),
    ]
