# Generated by Django 5.0 on 2024-02-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosfat', '0002_rename_cwizcenie_cwiczenie_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantreningowy',
            name='bmi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
