# Generated by Django 4.2.7 on 2024-02-20 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crosfat', '0002_plancwiczen_ilosc_pow_plancwiczen_nazwa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plancwiczen',
            name='cwiczenie_id',
        ),
        migrations.RemoveField(
            model_name='plancwiczen',
            name='cwiczenie_typ',
        ),
        migrations.RemoveField(
            model_name='plancwiczen',
            name='ilosc_pow',
        ),
        migrations.RemoveField(
            model_name='plancwiczen',
            name='nazwa',
        ),
        migrations.AddField(
            model_name='plancwiczen',
            name='cwiczenie_budowa_masy_miesniowej',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crosfat.cwiczenie_budowa_masy_miesniowej'),
        ),
        migrations.AddField(
            model_name='plancwiczen',
            name='cwiczenie_poprawa_wytrzymalosci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crosfat.cwiecznie_poprawa_wytrzymalosc'),
        ),
        migrations.AddField(
            model_name='plancwiczen',
            name='cwiczenie_utrata_wagi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crosfat.cwiczenie_utrata_wagi'),
        ),
    ]
